AWSTemplateFormatVersion: "2010-09-09"
Description: DT DNS stack
Parameters:
  #------------------------
  # Deployment Information
  #------------------------
  environment:
    Type: String
    Description: Name of the environment
    Default: production

  #-----------------------
  # Route53 Configuration
  #-----------------------
  Domain:
    Type: String
    Description: The HostedZoneName to create the endpoint on
  SubDomain:
    Type: String
    Description: The subdomain to be used by dt

  #-----------
  # Resources
  #-----------
  DtDNS:
    Type: String
    Description: Load balancer dns name for dt endpoint

Resources:
  DtEndpoint:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub "${Domain}."
      Comment: 'DNS name for dt'
      Name: !Sub "${SubDomain}.${Domain}."
      Type: CNAME
      TTL: '300'
      ResourceRecords:
        - !Ref DtDNS

Outputs:
  Endpoint:
    Description: 'DNS name for Defend Together'
    Value: !Sub "${SubDomain}.${Domain}."