name: Auth Test

on:
  push:
    branches:
      - feature/scaling


jobs:
  authorizer-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100'
      - name: Install Packages
        working-directory: authorizer
        run: |
          dotnet add package StackExchange.Redis --version 2.1.39 --source https://www.myget.org/F/stackoverflow/api/v3/index.json
      - name: Build
        working-directory: authorizer
        run: |
          dotnet build --configuration Release  
      - name: Push Tag to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          BUILD_PATH: "authorizer"
          DOCKERFILE: "authorizer/Dockerfile"
          IMAGE_NAME: "josephbmanley/defend-together-authorizer"
          TAG_NAME: "stage"
          LATEST: "false"